In [2]:
import numpy as np

In [3]:
arr_0D = np.array(2)
arr_1D = np.array([1,2,3,4,5])
arr_2D = np.array([[1,2,3] , [4,5,6]])

dimensions_1 = (arr_1D.ndim)
print(dimensions_1)

1


In [7]:
dimensions_2 = (arr_2D.ndim)
print(dimensions_2)

2


In [9]:
dimensions_0 = (arr_0D.ndim)
print(dimensions_0)

0


In [10]:
print(arr_2D[0,1])

2


In [11]:
print(arr_2D)

[[1 2 3]
 [4 5 6]]


In [12]:
print(arr_1D)

[1 2 3 4 5]


In [13]:
print(arr_1D[1:3:2])

[2]


In [14]:
print(arr_1D[0:4:2])

[1 3]


In [15]:
print(arr_2D[1,0:3])

[4 5 6]


In [16]:
print(arr_2D[0:2, 1:4])

[[2 3]
 [5 6]]


In [17]:
print(arr_1D[-1:2])

[]


In [18]:
print(arr_1D[-1:0:2])

[]


In [20]:
print(arr_2D[1,-1])

6


In [21]:
print(arr_1D[-1])

5


In [22]:
print(arr_1D[-1:1:1])

[]


In [23]:
print(arr_1D[-1:-5:2])

[]


In [25]:
print(arr_1D[1:-1:2])

[2 4]


In [27]:
print(arr_1D[-1:-5:-2])

[5 3]


In [33]:
arr = np.array([1,2,3,4,5,6,7,8])
arr.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [34]:
for x in arr_1D:
    print(x)

1
2
3
4
5


In [36]:
for x in arr_2D:
    for y in x:
        print(y)

1
2
3
4
5
6


In [39]:
arr = np.array([7,5,3,2,8])

In [40]:
np.sort(arr)

array([2, 3, 5, 7, 8])

In [41]:
from numpy import random

In [42]:
random.randint(100)

81

In [43]:
np.where(arr==8)

(array([4]),)

In [44]:
np.zeros((5,), dtype = int)

array([0, 0, 0, 0, 0])

In [50]:
np.pad(arr, (2,), 'mean')

array([5, 5, 7, 5, 3, 2, 8, 5, 5])

In [51]:
np.save('output', arr)

In [52]:
a = np.load('output.npy')

In [53]:
print(a)

[7 5 3 2 8]
